### PR TITLE
new home page

### PR DESCRIPTION
**Pull request by MaMH20**
I have designed a responsive homepage for the glossary and added  language switch button @JonasCir 

My idea is that the user should  select the language and after that he will be able to see the glossary.

Screenshot from 2021-05-28 17-32-12

### CODE REVIEW

**Comment by bernardsilenou** [comment]
@MaMH20 
This looks good, great Job!
Can we not put English as the default page?

**Comment by JonasCir** [comment]
I'm a little bit scared about the 5000+ files :D Where does this come from?

**Comment by MaMH20** [comment]
@bernardsilenou yes it is possible. And  that will be the next step.

**Comment by MaMH20** [comment]
@JonasCir  I understand what you mean. But with this structure we can build more features.  What #Mkdocs only can't provide us with.

But if the the wish is to keep it simple. We can keep it as it is. And  try to play around to  get the results what we want.

The source  https://github.com/mkdocs/mkdocs i

**Comment by JonasCir** [comment]
Alright, if we aim for more flexibility, I think other technologies like Jekyll might be a better option. I think I dropped some links #31 which show to setup more languages there. But adding 5000+ raw assets to git such that they show up in GitHub pages is a little bit out of proportion :D

**Comment by MaMH20** [comment]
@JonasCir  you are right.

I just realized now what you mean with 5000+ files  :D 😅
It is not how it supposed to be :D

**Pull request closed without merging**
